[package]
name = "hlwall"
version = "0.0.1"
authors = ["Fedcomp"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.11", features = ["full"] }
log = "0.4.8"
env_logger = "0.7.1"
bytes = "0.5.4"
byteorder = "1.3.4"
thiserror = "1.0.11"
anyhow = "1.0.26"
